from typing import Any, Callable, Coroutine, Dict, Iterable, Optional, Type, Union

from .clans import Clan
from .client import Client
from .players import ClanMember, Player
from .war_attack import WarAttack
from .wars import ClanWar

_ClanType = Type[Clan]
_PlayerType = Type[Player]
_WarType = Type[ClanWar]
_CustomClassType = Union[_ClanType, _PlayerType, _WarType]
_EventPredicateClasses = Union[Clan, Player, ClanWar, ClanMember, WarAttack]
_EventCallbackType = Callable[[_EventPredicateClasses, _EventPredicateClasses], Coroutine]
_EventCallbackCustomArgumentsType = Callable[..., Coroutine]
_EventPredicateType = Callable[[_EventPredicateClasses, _EventPredicateClasses], bool]
_EventWrappedPredicateType = Callable[
    [_EventPredicateClasses, _EventPredicateClasses, _EventCallbackType], Coroutine[None]
]
_EventDecoratorReturn = Callable[[_EventCallbackType], _EventCallbackType]

_Tags = Optional[Iterable[str]]
_Retry = Optional[int]


class Event:
    runner: Callable
    callback: Callable
    tags: tuple
    type: str

    def __init__(self, runner: Callable, callback: Callable, tags: tuple, type_: str) -> None: ...
    def __call__(self, cached: Any, current: Any) -> Coroutine: ...
    @classmethod
    def from_decorator(cls, func: Callable, runner: Callable) -> "Event": ...


class ClanEvents:
    event_type: str

    @classmethod
    def name(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
             retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def badge(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
              retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def level(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
              retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def points(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
               retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def versus_points(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                      retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def builder_base_points(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                            retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_count(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                     retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def location(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                 retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def type(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
             retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def required_trophies(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                          retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def war_frequency(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                      retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def war_win_streak(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                       retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def war_wins(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                 retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def war_ties(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                 retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def war_losses(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                   retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def public_war_log(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                       retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def war_league(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                   retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def labels(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
               retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def description(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                    retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_exp_level(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                         retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_league(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                      retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_trophies(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                        retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_clan_rank(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                         retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_clan_previous_rank(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_versus_trophies(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                               retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_builder_base_trophies(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                                     retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_versus_rank(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                           retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_builder_base_rank(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                                 retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_donations(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                         retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_received(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                        retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_name(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                    retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_role(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                    retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_join(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                    retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def member_leave(cls, tags: _Tags = None, custom_class: Optional[_ClanType] = None,
                     retry_interval: _Retry = None) -> _EventDecoratorReturn: ...


class PlayerEvents:
    event_type: str

    @classmethod
    def achievement_change(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                           retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def name(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
             retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def exp_level(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def trophies(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                 retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def versus_trophies(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                        retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def builder_base_trophies(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                              retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_rank(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_previous_rank(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                           retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def donations(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def received(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                 retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def league(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
               retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def role(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
             retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def best_trophies(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                      retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def war_stars(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def town_hall(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def town_hall_weapon(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                         retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def builder_hall(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                     retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def best_versus_trophies(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                             retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def versus_attack_wins(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                           retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def best_builder_base_trophies(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                                   retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def legend_statistics(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                          retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def labels(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
               retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def equipment_change(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                         retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def active_equipment_change(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                                retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def troop_change(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                     retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def spell_change(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                     retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def hero_change(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                    retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def joined_clan(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                    retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def left_clan(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_name(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                  retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_badge(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                   retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_level(cls, tags: _Tags = None, custom_class: Optional[_PlayerType] = None,
                   retry_interval: _Retry = None) -> _EventDecoratorReturn: ...


class WarEvents:
    event_type: str

    @classmethod
    def war_attack(cls, tags: _Tags = None, custom_class: Optional[_WarType] = None,
                   retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def state(cls, tags: _Tags = None, custom_class: Optional[_WarType] = None,
              retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def members(cls, tags: _Tags = None, custom_class: Optional[_WarType] = None,
                retry_interval: _Retry = None) -> _EventDecoratorReturn: ...
    @classmethod
    def new_war(cls, tags: _Tags = None, custom_class: Optional[_WarType] = None,
                retry_interval: _Retry = None) -> _EventDecoratorReturn: ...


class ClientEvents:
    event_type: str

    @classmethod
    def maintenance_start(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def maintenance_completion(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def new_season_start(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def raid_weekend_start(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def raid_weekend_end(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_games_start(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_games_end(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def keys_reset(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def event_error(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_loop_start(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def clan_loop_finish(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def player_loop_start(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def player_loop_finish(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def war_loop_start(cls) -> _EventDecoratorReturn: ...
    @classmethod
    def war_loop_finish(cls) -> _EventDecoratorReturn: ...


class EventsClient(Client):
    clan_retry_interval: int
    player_retry_interval: int
    war_retry_interval: int
    maintenance_player_tag: str

    clan_cls: Type[Clan]
    player_cls: Type[Player]
    war_cls: Type[ClanWar]

    _player_updates: set
    _clan_updates: set
    _war_updates: set

    _listeners: Dict
    _updater_tasks: Dict[str, Any]
    _tasks_loop: Optional[Any]
    _data_maxsize: int

    is_cwl_active: bool
    check_cwl_prep: bool
    raid_clan_tag: Optional[str]

    clan_loops_run: int
    player_loops_run: int
    war_loops_run: int

    async def close(self) -> None: ...
    async def login(self, email: str, password: str) -> None: ...
    def login_with_keys(self, *keys: str) -> None: ...
    async def login_with_tokens(self, *tokens: str) -> None: ...
    def add_clan_updates(self, *tags: str) -> None: ...
    def add_player_updates(self, *tags: str) -> None: ...
    def add_war_updates(self, *tags: str) -> None: ...
    def remove_clan_updates(self, *tags: str) -> None: ...
    def remove_player_updates(self, *tags: str) -> None: ...
    def remove_war_updates(self, *tags: str) -> None: ...
    def event(self, event: Callable) -> Callable: ...
    def add_events(self, *events: Callable) -> None: ...
    def remove_events(self, *events: Callable) -> None: ...
    def dispatch(self, event_name: str, *args: Any, **kwargs: Any) -> None: ...
    def run_forever(self) -> None: ...
